version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPOSITORY:$IMAGE_TAG -f analytics/Dockerfile analytics || (echo "Docker build failed" && exit 1)

      - docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REPOSITORY:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $ECR_REPOSITORY:$IMAGE_TAG
      - echo Build completed on `date`
 