apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowork
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowork
  template:
    metadata:
      labels:
        app: cowork
    spec:
      containers:
        - name: cowork
          image: 711267344123.dkr.ecr.us-east-1.amazonaws.com/coworking:0.0.1
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: "/readiness_check"
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5

          env:
          - name: APP_PORT
            value: "5153"
          - name: POSTGRES_HOST
            value: postgres-postgresql
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-postgresql
                key: postgres-password

          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cowork
spec:
  selector:
    app: cowork
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
