apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-manual-pvc
spec:
  storageClassName: ebs-sc # This should match the storageClassName of the PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # This should be equal or less than the capacity of the PV
